# -*- coding: utf-8 -*-
# @Author: Diogo Telheiro do Nascimento
# @Date:   2022-03-15 20:18:55
# @Last Modified by:   Diogo Telheiro do Nascimento
# @Last Modified time: 2022-03-20 14:29:18
version: '3.4'

services:
  myenv:
    build:
      context: ./docker/
      dockerfile: ${DOCKERFILE}
      args:
        USERNAME: ${UNAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    image: ${IMAGE_NAME}:latest
    ports:
      - "8000:8000"
    user: "${USER_UID}:${USER_GID}"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    volumes:
      - .:/workspace
      - type: bind
        source: ${GITCONFIG}
        target: /home/${UNAME}/.gitconfig
        volume: 
          nocopy: true
        read_only: true
      
    working_dir: ${WORKDIR}
    
    command: jupyter notebook --ip=0.0.0.0 --port=8000
